"use client"
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const clash = localFont({
  src: [
    {
      path: "../../assets/fonts/clash/ClashDisplay-Bold.otf",
      weight: "400",
      style: "normal",
    },
  ],
});
export const mont = localFont({
  src: [
    {
      path: "../../assets/fonts/montserrat/Montserrat-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mont.className}>{children}</body>
    </html>
  );
}
